<?php
function tapit_maps_leaflet_map_info() {
  return array(
    'custom map' =>
    array(
      'label' => 'custom map',
      'description' => t('Leaflet map with custom zoom settings.'),
      'settings' => array(
        'dragging' => TRUE,
        'touchZoom' => TRUE,
        'scrollWheelZoom' => TRUE,
        'doubleClickZoom' => TRUE,
        'zoomControl' => TRUE,
        'attributionControl' => TRUE,
        'trackResize' => TRUE,
        'fadeAnimation' => TRUE,
        'zoomAnimation' => TRUE,
        'closePopupOnClick' => TRUE,
        'layerControl' => FALSE,
        'maxZoom' => 18,
        'zoom' => 6,
      ),
      'center' => array(
      'lat' => -30, 
      'lon' => 25),
      'layers' => array(
        'earth' => array(
          'urlTemplate' => 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          'options' => array(
            'attribution' => 'custom map'
          )
        ),
      ),
    ),
  );
}
?>

