<?php
/**
 * @file
 * tapit_stores.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tapit_stores_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'FINRO Jumbo',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '02902413-c20a-4cf4-bd95-87a1ccf4db9b',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Pinetown',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '03ea7892-090b-473e-8ad2-f45bdd8f43b6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'JNB',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '05c3ba30-f60c-433b-ba88-83ef8f30ed89',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '88b090e1-292c-4f4b-b463-741b7d1e4aea',
    ),
  );
  $terms[] = array(
    'name' => 'Cape Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '08edaacf-15a0-434c-9008-5e50dd14ebbe',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'e391fca9-a4fc-4cd6-9c7d-85858c8fe6b5',
    ),
  );
  $terms[] = array(
    'name' => 'clermont',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0a1790ce-feb8-43ba-97d6-2f737b0f8957',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'PE',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0d4137eb-8426-49a2-b073-f862a3e76a04',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Greytown',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0e6cf249-21cb-458d-b09c-5be9d043df3f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mkuze',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0e851b28-0148-4281-b02e-003879217b98',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Ngwelezani',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '12551259-d4a6-4c31-9e79-0e68e1ada97e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Gingindlovu',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '14929d29-eef4-4722-8f35-e9fd341abbad',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Browns Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '15bf854d-4216-c664-616f-5b1628d54401',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Pietermaritzburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '16d90535-1065-4d3d-b5e2-1babae84202c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Kieskamahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1e34ffa8-f677-43f3-ba19-ddacd50de38b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Vodacom (IP)',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '2dbe10d9-9b81-c414-45ca-a5429699266d',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Fort Beaufort',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2f4474cd-7810-495e-8b1b-8b4faad396fb',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Queensburgh',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '37cb54e4-b396-4ebd-a0d7-0d8a57df4e3b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mdantsane',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3c606f6b-241f-456a-bbf2-36e19af2eb1f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Kwambonambi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3d18b715-6250-4bfb-b9de-c729fd4027b4',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3f033dad-022a-5ec4-09dd-fe3da699c58b',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'South Africa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
  );
  $terms[] = array(
    'name' => 'Newcastle',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '451da009-0566-40c6-96c5-605bebab2e3b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Vodafone SmartTab10 Android 3.2',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4b06cad7-9f94-38e4-718e-97ea6b2dbd66',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry PE',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4c2e5360-8be7-9b94-014f-fae2bf31a151',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Empangeni Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4df22267-618b-e6d4-5dd3-79902b89db3d',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Small',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '54ff1a31-1c29-c074-0da6-047f17d3b17e',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Vodacom',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '56e3b065-884b-c824-9d1d-b183d6aca3a5',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Pennington',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5aa510de-3813-4c55-9945-92b0e49daa77',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mandonella',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5be965db-f1f8-41fd-94b6-041b66ac5f3c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Jumbo Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '5ca9813e-cf82-3e84-fd9e-0c2652a96735',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Umlazi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5ddc4879-5584-4fc2-9a3f-523c309dce7d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Stanger',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5dde3019-28e3-4a92-860d-ca3d625f7f80',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Jumbo Ottery',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '60b99524-e9fa-d534-c1b8-e18971d8bdfb',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Mboza',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '60d3847b-aa0a-46a6-8594-fb4c8d35a6bb',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Kwajobe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '62236805-dd68-4823-9555-4060a2766eb6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mpumalanga',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6378b008-5c24-4f60-95c9-b875beaadfc8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    ),
  );
  $terms[] = array(
    'name' => 'Cape Province',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '672a8c25-daad-4abc-97b2-5ccaa1374e3b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'e391fca9-a4fc-4cd6-9c7d-85858c8fe6b5',
    ),
  );
  $terms[] = array(
    'name' => 'Vodaphone Smart tab10 android 13.2',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6fa29923-6562-12b4-6dfe-3709adb8687d',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Middledrift',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7495986f-3f11-4550-ae85-f48beaa3aba4',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Eshowe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7fc4cde9-74cd-49fb-a5ce-1608d8e381f1',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mkhuze',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '809467b7-8020-49b2-8c73-04f58b910ce5',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'UMZINTO',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '840879f2-dc46-499e-94db-c35ad1f7939e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '854f857b-1bc2-c6d4-bd49-73c3ee8de7a7',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Hlabisa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '870004fe-8811-4d64-b7fd-3df24acd058f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Gauteng',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '88b090e1-292c-4f4b-b463-741b7d1e4aea',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    ),
  );
  $terms[] = array(
    'name' => 'Hillcrest',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8bc5da45-0c27-453e-a60b-176ad021f4c9',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'King Williams Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8c4f33c3-ba33-4dff-a657-9226cfd39117',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Chatsworth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8cd6e6d5-3cd5-4905-91d4-33c0899b301e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Vodacom / MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '8e71e416-8c67-f6e4-39b7-052f06bca3c8',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Pietermarutzbueg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8f02d96e-2f02-4494-98aa-e8b8a321a478',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Alice',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '903ac838-0c35-4f58-b049-d57290a831ab',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Mbazwana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '91564259-a300-49a9-bc79-89d128aa3b12',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Samsung Galaxy Tab 2 10.1',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '92174f41-43c1-5e24-9105-7433b00e4a27',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Eastern Cape',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    ),
  );
  $terms[] = array(
    'name' => 'Jozini',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '97481afd-5f65-4963-aca3-ee9e345c0aa9',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Kingwilliams town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '99a1c378-9861-4724-9f87-d56da16c21d8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'New Germany',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9f66a123-fb86-43de-a298-bd52f949a728',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Empangeni',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a06e3a4d-7faf-443d-b15f-50761fc39238',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Keiskamahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a19699a2-cef1-4137-94d0-66dc3cbb3ffd',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Port Elizabeth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a2925c69-86af-4fd0-8379-3a6d6d531a24',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Southbroom',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a4c07e11-8d54-46b8-864d-43858437b851',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'KwaZulu Natal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    ),
  );
  $terms[] = array(
    'name' => 'p.m.b',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a9687cc1-a81a-4d4f-86a8-2143d311c281',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Nkonkobe Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'aad45025-fb3c-f0d4-99ca-bc0281b6ba59',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Durban',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'abf095bf-7efe-443c-a651-231018aeb591',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Durban Central',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ac6d4dc1-e397-4e66-aa55-69b265069413',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Ndengezi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'acecb052-7fc7-41ec-b228-ced2e051af9b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Jumbo Epping',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'b31e2de1-eeaa-b064-c115-aa7e4d54d90f',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Mduku',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bb690eb0-f90f-4056-832e-bc0345630412',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Hluhluwe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'be8a5099-b981-4e3d-8735-6e09a9841784',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Underburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c09045ce-1bfe-4026-8524-0cd8df308604',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Estcourt',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c3d5ee62-9cc3-4267-bf9a-cd732fb053a0',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Kwadlangezwa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c4521c7a-b271-4a87-9a32-5578dbcda7f3',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Mtuba',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c4fff167-bb58-402e-a7aa-67f5b49498c6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Dalton',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cc4352d8-14c1-451d-917d-bcbefebb8bd6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Large',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd11ace8f-21fe-c8d4-1130-34e105ef28ec',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'East London',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd5226bc0-3365-41d8-96aa-96d601884521',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Richards Bay',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd6afcdb0-e83f-49a3-bf33-ba7f69c5ea1f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Cape Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd708e7cf-f71c-4d54-a85e-312c2a476a2e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'pietermarizburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd76e8cde-1fd7-4828-a1e7-0f34cfd2f67e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Johannesburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8e854a4-003e-40c8-a171-0592c3e52367',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '88b090e1-292c-4f4b-b463-741b7d1e4aea',
    ),
  );
  $terms[] = array(
    'name' => 'Westmead Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd9ab6b6e-8afc-f164-dd9b-de4db748eb3e',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Esikhawini',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'da351449-4ce0-4aea-b37e-4b5ba7492e1d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'DBN',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ddd93d81-76c6-413d-838f-26d9d3c0de86',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '6378b008-5c24-4f60-95c9-b875beaadfc8',
    ),
  );
  $terms[] = array(
    'name' => 'Nyuswa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e028f1b0-86a0-4ea0-ba05-b4ada6017fc5',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry EL',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e1120e3f-d0d6-9cd4-dda1-a364c760f645',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Melmoth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e1d812d7-bb12-47ab-b62a-3ce8116a014f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e2978b69-dcb3-faf4-4d6b-ac7962999c62',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Despatch',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e2c2fb87-a41b-4dea-bc19-2f72fa08fa36',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Western Cape',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e391fca9-a4fc-4cd6-9c7d-85858c8fe6b5',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '42b004a8-3433-44ec-b64a-ea48249d47fe',
    ),
  );
  $terms[] = array(
    'name' => 'Westville',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e52409d8-b751-48be-b534-a268dc6afddd',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Medium',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e8e8e619-733f-6124-6980-fe074613ddb0',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Port Shepstone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ed03300b-d839-474c-ac83-16640d02233f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'Adelaide',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f611ce7d-6768-474b-bc22-8c466a748687',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  $terms[] = array(
    'name' => 'Pongola',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f6e38832-780f-41f6-86b0-81993a3e53f9',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'a6e3c8e7-d221-40af-a40d-189355e69ea2',
    ),
  );
  $terms[] = array(
    'name' => 'King Williams Town Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'fea9632b-1e89-27e4-19a2-ebbf61685715',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Keiskammahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ffe5b71d-7299-4a9f-8458-738572cd25c3',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '95fd3b86-b3a7-4091-80f8-ab065acfae05',
    ),
  );
  variable_set('uuid_features_file_types', array());
  variable_set('uuid_features_file_mode', 'inline');
  variable_set('uuid_features_file_assets_path', '');
  variable_set('uuid_features_file_supported_fields', 'file, image');
  return $terms;
}
