<?php
/**
 * @file
 * tapit_stores.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tapit_stores_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'Mandonella',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0046a895-db6d-4275-a271-f0643f0a2691',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'clermont',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '01a7661b-edd1-425f-bd18-ead8630f6092',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'FINRO Jumbo',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '02902413-c20a-4cf4-bd95-87a1ccf4db9b',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Westville',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '036ba7e1-5017-4997-a6cd-beda07cc1e20',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Port Elizabeth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '04215ed4-f0eb-437e-97dd-889cfb64272e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'UMZINTO',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0ca4e199-b5a3-4657-baa4-9c836ee455e8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Greytown',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '122316b1-f3df-4c64-a9f9-27e88073411c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Mkhuze',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '14391448-e99e-40ea-a301-fcf3f29564eb',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Browns Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '15bf854d-4216-c664-616f-5b1628d54401',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Hluhluwe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1627e1da-1994-4137-8e2c-05f48315b2b7',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'KwaZulu Natal',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    ),
  );
  $terms[] = array(
    'name' => 'Eastern Cape',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    ),
  );
  $terms[] = array(
    'name' => 'Durban',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '21a91c75-4b1c-4594-a1de-03c051ecbd67',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Dalton',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '22b60807-4a44-4076-ac98-e5409f55ca25',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Mbazwana',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '254fccba-d646-4722-837a-811df6f1885f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Vodacom (IP)',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '2dbe10d9-9b81-c414-45ca-a5429699266d',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Mkuze',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2de4b486-0cc8-41dd-aedb-8030d3f5bfb5',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Durban Central',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '333d5c48-403e-4641-9d65-6b3d489b71f8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Mboza',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '33af6c00-3dbe-43ac-9bb6-f21150e20279',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'p.m.b',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '38bebf3c-a129-498a-b7ed-a5ef246a6b12',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Keiskamahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3c9ae3d3-1411-427c-93ee-e934846b2bfa',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3f033dad-022a-5ec4-09dd-fe3da699c58b',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Kwadlangezwa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4149a834-60ea-4d99-987c-2de9db9c304c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Western Cape',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '43208f24-776d-49a5-80ff-05633911d7ce',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    ),
  );
  $terms[] = array(
    'name' => 'ZA',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
  );
  $terms[] = array(
    'name' => 'JNB',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '46635154-e2bd-47a5-8826-07f4d79e8ed6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'c9e2a1a5-284a-47b1-8036-91cb20b8aaa8',
    ),
  );
  $terms[] = array(
    'name' => 'Middledrift',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '481e2678-8bdc-44dd-bbfd-01990dab80e6',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Vodafone SmartTab10 Android 3.2',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4b06cad7-9f94-38e4-718e-97ea6b2dbd66',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Ngwelezani',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4b29b6dd-87ca-4803-a052-06d5a3293cd9',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry PE',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4c2e5360-8be7-9b94-014f-fae2bf31a151',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Cape Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4db1983e-6808-4652-9f7a-8286f8d5bf62',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '43208f24-776d-49a5-80ff-05633911d7ce',
    ),
  );
  $terms[] = array(
    'name' => 'Empangeni Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4df22267-618b-e6d4-5dd3-79902b89db3d',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Esikhawini',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4df56dad-d1fd-4d47-b7b9-97eb53843d3c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Kieskamahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4f1c0cf5-b676-4b37-ad61-043deeac4956',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Port Shepstone',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '50e2b99a-55ff-477f-b22c-0d4cada7782d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Keiskammahoek',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '52cfc3c0-edac-415a-b09b-15179a8c8c0d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Melmoth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '535194c5-fa92-4abf-8a4a-551ed6491414',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Small',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '54ff1a31-1c29-c074-0da6-047f17d3b17e',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Ndengezi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '56b06ae5-56dc-47c0-aff9-a6de5627505b',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Vodacom',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '56e3b065-884b-c824-9d1d-b183d6aca3a5',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Jumbo Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '5ca9813e-cf82-3e84-fd9e-0c2652a96735',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Jumbo Ottery',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '60b99524-e9fa-d534-c1b8-e18971d8bdfb',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Gingindlovu',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6151e194-b518-472c-abbe-880d910cb7ef',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Pennington',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '624788c1-87ce-4552-9398-23133dffb012',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Johannesburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '67d3d4ff-0a1d-4c2f-a2ca-dcea81974b0a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => 'c9e2a1a5-284a-47b1-8036-91cb20b8aaa8',
    ),
  );
  $terms[] = array(
    'name' => 'DBN',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '69f7e3d8-aaff-4e61-8c15-01df5d07978c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '7ac2b164-caf5-42f4-9158-a1ed1d00791a',
    ),
  );
  $terms[] = array(
    'name' => 'Cape Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6b170408-7517-4aec-be20-12e50436285d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Jozini',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6d2211c2-2736-45c4-9772-8dd7bbdcf646',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'PE',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6dfeef19-c85a-4ca9-b7c9-6c19d1090b14',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Vodaphone Smart tab10 android 13.2',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6fa29923-6562-12b4-6dfe-3709adb8687d',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Pinetown',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '70e5893e-0aa2-4dad-aabf-b128b6a83ae8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Umlazi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '71078d24-0293-42a4-b1c2-b32f04856ca1',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Hlabisa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '77979cd8-aa2d-4ca0-be0c-4eee59b6c94a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Cape Province',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7a8d931f-fdce-4d74-ab3c-aac53c37478d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '43208f24-776d-49a5-80ff-05633911d7ce',
    ),
  );
  $terms[] = array(
    'name' => 'Mpumalanga',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7ac2b164-caf5-42f4-9158-a1ed1d00791a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    ),
  );
  $terms[] = array(
    'name' => 'East London',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '7f39a07f-4fe3-43ee-aa55-fa505c496494',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'pietermarizburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '85234b11-bf3f-4a0c-ac31-458998478a8a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '854f857b-1bc2-c6d4-bd49-73c3ee8de7a7',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Underburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '87d99e77-cda3-4bf4-a720-f706c5d45c5f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Queensburgh',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8c5305dd-ee61-4f66-9727-3e52b997eb94',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Hillcrest',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8dd527b9-b7d4-46dc-8410-1333af559414',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Vodacom / MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '8e71e416-8c67-f6e4-39b7-052f06bca3c8',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Despatch',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8e9b54c8-0fd6-4ef9-9954-ff8c3a90e56a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Samsung Galaxy Tab 2 10.1',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '92174f41-43c1-5e24-9105-7433b00e4a27',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Mduku',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '93f7b73a-acbd-471a-9a70-e39b992dc189',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Estcourt',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '98507db6-ac11-454d-a8b7-b02ca7bd405d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Pietermarutzbueg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9c70cff3-0550-4a33-9ead-b6c93cfe2cf9',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Stanger',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e3060a2-339a-44f5-acad-d16edd1b57b3',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Chatsworth',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a1ef81d9-532c-4d7b-a8d4-8f11e63b7259',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Nyuswa',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a64a6b48-ebe7-49fa-895d-5286891715f1',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Kwambonambi',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a747c475-d7f0-48a8-b39c-d7957975892c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Nkonkobe Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'aad45025-fb3c-f0d4-99ca-bc0281b6ba59',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Kingwilliams town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ab82ca9a-eb4b-42fd-a748-807c091ad6f0',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'New Germany',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'aec90216-2357-44de-8791-f0eb2a53a1cd',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Fort Beaufort',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b1438e13-27ee-4b18-96fd-1c302c814ed0',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Jumbo Epping',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'b31e2de1-eeaa-b064-c115-aa7e4d54d90f',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Mdantsane',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b57ede04-33e7-43b7-80e2-5a7789b8186f',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Pietermaritzburg',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b75f4e24-032c-4919-9fa4-c7023113caeb',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Eshowe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b978a762-4c6c-4b31-98e4-4cee45e9718d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Empangeni',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bf1be834-72c9-47e1-9dac-ce2252563727',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Pongola',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c459e9c6-60d8-4b9b-aa0c-944f1a967b2d',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Gauteng',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c9e2a1a5-284a-47b1-8036-91cb20b8aaa8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '44ddc3a4-3e3e-421f-ab5c-a085733ef96d',
    ),
  );
  $terms[] = array(
    'name' => 'Large',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd11ace8f-21fe-c8d4-1130-34e105ef28ec',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Westmead Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd9ab6b6e-8afc-f164-dd9b-de4db748eb3e',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Mtuba',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'df58b466-2aca-4588-89c9-41f2f88ac0d8',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry EL',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e1120e3f-d0d6-9cd4-dda1-a364c760f645',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e2978b69-dcb3-faf4-4d6b-ac7962999c62',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'King Williams Town',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e3ee73db-d16b-4218-a80d-7212f29634ef',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Adelaide',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e755ba4e-e11e-46b6-a18e-cbe85558a29c',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Medium',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e8e8e619-733f-6124-6980-fe074613ddb0',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Southbroom',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eeda4378-3de1-485c-b251-96e63fb6518a',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Alice',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f4af739c-14a3-4780-9a60-4c1453d3d73e',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1f7ba6ab-963a-40ba-ae0a-e80edacf1d78',
    ),
  );
  $terms[] = array(
    'name' => 'Richards Bay',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f5382ca3-c82a-40e3-aa36-f8928f7cc8cc',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Newcastle',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f5cf5088-072a-4c38-9dfd-631e9f098667',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'Kwajobe',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fd576b60-8099-4851-bc31-09a6c854e708',
    'vocabulary_machine_name' => 'location_taxonomize',
    'location_taxonomize_longname' => array(),
    'parent' => array(
      0 => '1aa56e8b-7b82-4712-af8e-e3dbda262ab1',
    ),
  );
  $terms[] = array(
    'name' => 'King Williams Town Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'fea9632b-1e89-27e4-19a2-ebbf61685715',
    'vocabulary_machine_name' => 'wholesaler',
  );
  variable_set('uuid_features_file_types', array());
  variable_set('uuid_features_file_mode', 'inline');
  variable_set('uuid_features_file_assets_path', '');
  variable_set('uuid_features_file_supported_fields', 'file, image');
  return $terms;
}
