<?php
/**
 * @file
 * tapit_stores.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function tapit_stores_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'FINRO Jumbo',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '02902413-c20a-4cf4-bd95-87a1ccf4db9b',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Browns Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '15bf854d-4216-c664-616f-5b1628d54401',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Vodacom (IP)',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '2dbe10d9-9b81-c414-45ca-a5429699266d',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3f033dad-022a-5ec4-09dd-fe3da699c58b',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Vodafone SmartTab10 Android 3.2',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4b06cad7-9f94-38e4-718e-97ea6b2dbd66',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry PE',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4c2e5360-8be7-9b94-014f-fae2bf31a151',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Empangeni Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '4df22267-618b-e6d4-5dd3-79902b89db3d',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Small',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '54ff1a31-1c29-c074-0da6-047f17d3b17e',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Vodacom',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '56e3b065-884b-c824-9d1d-b183d6aca3a5',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Jumbo Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '5ca9813e-cf82-3e84-fd9e-0c2652a96735',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Jumbo Ottery',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '60b99524-e9fa-d534-c1b8-e18971d8bdfb',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Vodaphone Smart tab10 android 13.2',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6fa29923-6562-12b4-6dfe-3709adb8687d',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '854f857b-1bc2-c6d4-bd49-73c3ee8de7a7',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Vodacom / MTN',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '8e71e416-8c67-f6e4-39b7-052f06bca3c8',
    'vocabulary_machine_name' => 'service_provider',
  );
  $terms[] = array(
    'name' => 'Samsung Galaxy Tab 2 10.1',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => '92174f41-43c1-5e24-9105-7433b00e4a27',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Nkonkobe Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'aad45025-fb3c-f0d4-99ca-bc0281b6ba59',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Jumbo Epping',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'b31e2de1-eeaa-b064-c115-aa7e4d54d90f',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Large',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd11ace8f-21fe-c8d4-1130-34e105ef28ec',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'Westmead Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'd9ab6b6e-8afc-f164-dd9b-de4db748eb3e',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'Weirs Cash & Carry EL',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e1120e3f-d0d6-9cd4-dda1-a364c760f645',
    'vocabulary_machine_name' => 'wholesaler',
  );
  $terms[] = array(
    'name' => 'N/A',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e2978b69-dcb3-faf4-4d6b-ac7962999c62',
    'vocabulary_machine_name' => 'device_type',
  );
  $terms[] = array(
    'name' => 'Medium',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'e8e8e619-733f-6124-6980-fe074613ddb0',
    'vocabulary_machine_name' => 'size',
  );
  $terms[] = array(
    'name' => 'King Williams Town Cash & Carry',
    'description' => '',
    'format' => 'html',
    'weight' => '0',
    'uuid' => 'fea9632b-1e89-27e4-19a2-ebbf61685715',
    'vocabulary_machine_name' => 'wholesaler',
  );
  variable_set('uuid_features_file_types', array());
  variable_set('uuid_features_file_mode', 'inline');
  variable_set('uuid_features_file_assets_path', '');
  variable_set('uuid_features_file_supported_fields', 'file, image');
  return $terms;
}
